- name: Copy docker-compose.yml
  copy:
    src: "{{ playbook_dir }}/../docker-compose.yml"
    dest: /opt/devops-project/docker-compose.yml

- name: Copy backend files
  copy:
    src: "{{ playbook_dir }}/../backend/"
    dest: /opt/devops-project/backend/
    mode: "0755"

- name: Copy frontend files
  copy:
    src: "{{ playbook_dir }}/../frontend/"
    dest: /opt/devops-project/frontend/
    mode: "0755"
